HAI 1.2
	CAN HAS STDIO?
	I HAS A INPUT
	I HAS A N
	GIMMEH INPUT
	IM IN YR LOOP UPPIN YR nop WILE DIFFRINT INPUT AN SMALLR OF INPUT AN 1
		BOTH SAEM MOD OF INPUT AN 3 AN 0, O RLY?
			YA RLY
				N R 0
			NO WAI
				BOTH SAEM MOD OF INPUT AN 3 AN 1, O RLY?
					YA RLY
						N R -1
					NO WAI
						N R 1
				OIC
		OIC
		VISIBLE INPUT AN " " AN N
		INPUT R QUOSHUNT OF SUM OF INPUT AN N AN 3
	IM OUTTA YR LOOP
	VISIBLE INPUT
KTHXBYE
